on:  
  workflow_call:
    inputs:
      runner_group:
        required: true
        type: string
      terraform_version:
        type: string
        default: 1.1.9
        description: The version of the Terraform CLI.
        required: false
      working_directory:
        type: string
        description: The folder with the Terraform files.
        required: true
      github_event_name:
        type: string
        required: true
      tag:
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      GIT_PIPE_TOKEN:
        required: true
      INFRACOST_API_KEY:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive
        working-directory: ${{ inputs.working_directory }}
  
  cost_projection:
    runs-on: ${{ inputs.runner_group }}
    name: Show cost projection
    env:
      TF_ROOT: ${{ inputs.working_directory }}
    steps:           
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.base.ref }}'
      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json
      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v2
      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${TF_ROOT} \
                         --format=json \
                         --compare-to=/tmp/infracost-base.json \
                         --out-file=/tmp/infracost.json
      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update
  plan:
    name: Plan
    runs-on: ${{ inputs.runner_group }}
    strategy:
      fail-fast: false
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: Initialize Terraform
        run: terraform init -input=false 
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}   
      - name: Plan Terraform
        id: plan
        run: terraform plan -input=false -no-color
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
